## NumPy Arrays

In [1]:
my_list = [1, 2, 3]

In [2]:
my_list

[1, 2, 3]

In [3]:
import numpy as np

In [4]:
arr = np.array(my_list)

In [5]:
arr

array([1, 2, 3])

In [6]:
my_mat = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Built-in Methods

#### arange

Return evenly spaced values within a given interval

In [9]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.arange(1, 11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
np.arange(1, 11, 2)

array([1, 3, 5, 7, 9])

#### zeros and ones

Generate arrays of zeros or ones

In [12]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [13]:
np.zeros(4)

array([0., 0., 0., 0.])

In [14]:
np.ones((2, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [15]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

#### linspace

Return evenly spaced numbers over a specified interval.

In [16]:
np.linspace(0, 5, 10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [17]:
np.linspace(0, 5, 50)

array([0.        , 0.10204082, 0.20408163, 0.30612245, 0.40816327,
       0.51020408, 0.6122449 , 0.71428571, 0.81632653, 0.91836735,
       1.02040816, 1.12244898, 1.2244898 , 1.32653061, 1.42857143,
       1.53061224, 1.63265306, 1.73469388, 1.83673469, 1.93877551,
       2.04081633, 2.14285714, 2.24489796, 2.34693878, 2.44897959,
       2.55102041, 2.65306122, 2.75510204, 2.85714286, 2.95918367,
       3.06122449, 3.16326531, 3.26530612, 3.36734694, 3.46938776,
       3.57142857, 3.67346939, 3.7755102 , 3.87755102, 3.97959184,
       4.08163265, 4.18367347, 4.28571429, 4.3877551 , 4.48979592,
       4.59183673, 4.69387755, 4.79591837, 4.89795918, 5.        ])

#### eye

Creates an identity matrix

In [18]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

#### random.rand

Create an array of the given shape and populate it with random samples from a uniform distribution over \[0, 1)

In [19]:
np.random.rand(2)

array([0.86821811, 0.07254599])

In [20]:
np.random.rand(3, 3)

array([[0.5874365 , 0.37072241, 0.23332463],
       [0.11950925, 0.77539986, 0.89246101],
       [0.19646804, 0.38016621, 0.57311714]])

In [21]:
np.random.rand(3, 3, 2)

array([[[0.19475856, 0.21615647],
        [0.07906585, 0.55790676],
        [0.70144488, 0.50108701]],

       [[0.97691549, 0.75976122],
        [0.99142194, 0.77797008],
        [0.14277441, 0.84789033]],

       [[0.16899392, 0.06017915],
        [0.0581146 , 0.34361063],
        [0.69169028, 0.54178042]]])

#### random.randn

Return a sample (or samples) from the "standard normal" distribution. Unlike rand which is uniform:

In [22]:
np.random.randn(2)

array([-0.41431334,  1.62264783])

In [23]:
np.random.randn(3, 4)

array([[-0.40018432,  0.04856946,  0.01471909,  0.18776643],
       [ 0.38406733, -1.56402931, -0.89659453, -0.66751338],
       [-1.21626422,  2.18071441,  1.01130635, -0.3431346 ]])

In [24]:
np.random.randn(3, 3, 2)

array([[[ 0.40236492,  1.25319285],
        [ 0.09487149, -1.75827977],
        [ 0.06137837, -0.04481659]],

       [[-1.33592973, -0.18938831],
        [-0.47776673, -0.3849556 ],
        [-0.46293192, -0.39757377]],

       [[ 1.28459578,  1.7513983 ],
        [ 0.15928586,  0.4134335 ],
        [-1.55973645, -0.40307091]]])

#### random.randint

Return random integers from low (inclusive) to high (exclusive).

In [25]:
np.random.randint(1, 20)

8

In [26]:
np.random.randint(1, 20, 10)

array([ 3,  5, 10, 14,  4, 19, 18, 10,  6,  6])

### Array Attributes and Methods

In [27]:
arr = np.arange(25)

In [28]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [29]:
rand_arr = np.random.randint(0, 50, 10)

In [30]:
rand_arr

array([34,  7, 17, 46,  8, 40, 29, 26, 26, 12])

#### reshape

Returns an array containing the same data with a new shape.

In [31]:
arr.reshape(5, 5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [32]:
arr.reshape(5, 2)

ValueError: cannot reshape array of size 25 into shape (5,2)

#### max, min

Return <code>max</code> or <code>min</code> values:

In [33]:
rand_arr

array([34,  7, 17, 46,  8, 40, 29, 26, 26, 12])

In [34]:
rand_arr.max()

46

In [35]:
rand_arr.min()

7

#### argmax, argmin

Return indexes of max or min values:

In [36]:
rand_arr

array([34,  7, 17, 46,  8, 40, 29, 26, 26, 12])

In [37]:
rand_arr.argmax()

3

In [38]:
rand_arr.argmin()

1

#### shape

<code>shape</code> is an attribute that arrays have (not a method):

In [39]:
# Vector
arr.shape

(25,)

In [40]:
arr = arr.reshape(5, 5)
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [41]:
arr.shape

(5, 5)

In [42]:
arr = arr.reshape(1, 25)

In [43]:
arr.shape

(1, 25)

In [44]:
arr = arr.reshape(25,1)

In [45]:
arr

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [46]:
arr.shape

(25, 1)

In [47]:
arr.dtype

dtype('int32')