## NumPy Indexing

In [1]:
import numpy as np

In [2]:
arr = np.arange(0, 11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
arr[2]

2

In [4]:
arr[1:5]

array([1, 2, 3, 4])

In [5]:
arr[0:5:2]

array([0, 2, 4])

In [6]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [7]:
arr[1:]

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [8]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

### Broadcasting

In [9]:
arr[0:5] = 100

In [10]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

### Slicing

In [11]:
arr = np.arange(0, 11)

In [12]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [13]:
slice_of_arr = arr[:6]

In [14]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [15]:
slice_of_arr[:] = 99

In [16]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

<b>Changes also occur in our original array!</b>

In [17]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [18]:
arr = np.arange(0, 11)

In [19]:
slice_of_arr = arr.copy()[:6]

In [20]:
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [21]:
slice_of_arr[:] = 99

In [22]:
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [23]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Indexing a 2D array (matrices)

The general format is <code>arr_2d[row][col]</code> or <code>arr_2d[row,col]</code>

In [24]:
arr_2d = np.arange(5, 50, 5).reshape(3, 3)

In [25]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [26]:
arr_2d[0]

array([ 5, 10, 15])

In [27]:
arr_2d[0][1]

10

In [28]:
arr_2d[0, 1]

10

In [29]:
arr_2d[-1]

array([35, 40, 45])

In [30]:
arr_2d[-1, -1]

45

### 2D array slicing

In [31]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [32]:
arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])

In [33]:
arr_2d[:2, 1]

array([10, 25])

In [34]:
arr_2d[:2, -1:]

array([[15],
       [30]])

In [35]:
arr_2d[:2, -1]

array([15, 30])

### Fancy Indexing

Fancy indexing allows you to select entire rows or columns out of order

In [36]:
arr_2d = np.zeros((10,10))

In [37]:
arr_2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [38]:
arr_length = arr_2d.shape[1]

In [39]:
arr_length

10

In [40]:
for i in range(arr_length):
    arr_2d[i] = i
    
arr_2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

Fancy indexing allows the following:

In [41]:
arr_2d[[2, 4, 6, 8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [42]:
arr_2d[[6, 4, 2, 7]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])